[package]
name = "clipboard"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = {version="0.5.1", features=["json"]}
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
redis = "0.8.0"
config = "0.15.11"
sha2 = "0.10.9"
hex = "0.4.3"
log = "0.4.27"
simplelog = "0.12.2"

